### ISSUE TITLE
Build Maintenance

### ISSUE THREAD

**Issue by labkey-susanh** [LabKey/server#659]
### Tasks
- [x]  Remove redundant identifiers for plugins
- [x] Update dependency versions
- [x] code review
- [x] TC review and merge
- [x] One more merge
