### ISSUE TITLE
[LabKey CI] Improve upgrade workflow for embedded Tomcat

### ISSUE THREAD

**Issue by labkey-tchad** [LabKey/server#725]
[[Issue 49706](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49706)]

LabKey embedded currently has very simple logic for when to extract modules into place. If it finds the 'labkeywebapp' directory or if the 'context.webAppLocation' property is defined, it assumes that everything is already in place.
This works fine for our current primarily scenarios, test deployments and containerized deployments, because they are always setting up a fresh installation. If we want to encourage folks to switch existing production servers to embedded, the embedded server should be able to update modules in an existing deployment.

### Tasks
- [x] [Spec](https://docs.google.com/document/d/1aGvAw7QZGx38ql4Dja4H1SAIqyQZ2HB6W4CM7LRiQz8/edit) - 2
- [x] Spec review - 1 @labkey-jony
- [x] Create `application.properties` template for distributions
- [x] Remove version from 'labkeyServer.jar' included in distributions
- [x] Remove 'server' subdirectory creation
  - Update Dockerfile repo
  - Update LabKeyServer
- [x] Move VERSION file into 'labkeywebapp' directory
- [x] Compare VERSION files during startup
- [x] Add 'application.properties' to embedded distributions
- [x] Update default full-text-search index location
- [x] Backup existing deployment before extracting new distribution
- [x] Add example service scripts to embedded distributions
- [x] Code review 
  - https://github.com/LabKey/Dockerfile/pull/62
  - https://github.com/LabKey/gradlePlugin/pull/200
  - https://github.com/LabKey/testAutomation/pull/1845
  - https://github.com/LabKey/platform/pull/5295
  - https://github.com/LabKey/server/pull/752
- [x] Document upgrade process
- [x] Merge
